# Generated by Django 4.2.2 on 2023-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_adminapp', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(related_name='products', to='custom_adminapp.category'),
        ),
    ]
