# Generated by Django 4.2.2 on 2023-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='default_value', max_length=250),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
