# Generated by Django 4.2.2 on 2023-07-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_alter_cart_cart_id_alter_cartitem_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
