# Generated by Django 4.2.2 on 2023-07-12 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_adminapp', '0006_variantimage_image2_variantimage_image3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartapp', '0005_whishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
    ]
