# Generated by Django 4.2.2 on 2023-07-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_rename_whishlist_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='variant',
        ),
    ]
