# Generated by Django 4.2.2 on 2023-07-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_adminapp', '0006_variantimage_image2_variantimage_image3'),
        ('cartapp', '0007_remove_wishlist_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_adminapp.variant'),
            preserve_default=False,
        ),
    ]
