# Generated by Django 4.2.2 on 2023-07-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_adminapp', '0006_variantimage_image2_variantimage_image3'),
        ('cartapp', '0011_alter_coupon_applicable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_adminapp.category'),
        ),
    ]
