# Generated by Django 4.2.2 on 2023-07-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0013_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon_is_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartapp.coupon'),
        ),
    ]
