# Generated by Django 4.2.2 on 2023-07-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0014_alter_cart_coupon_is_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
