# Generated by Django 4.2.2 on 2023-07-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0016_rename_min_amount_coupon_min_purchase_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
