# Generated by Django 4.2.2 on 2023-07-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
