# Generated by Django 4.2.2 on 2023-07-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_remove_order_phone_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
