# Generated by Django 4.2.2 on 2023-07-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='order_created_date',
        ),
    ]
