# Generated by Django 4.2.2 on 2023-07-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_rename_order_date_order_order_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='varaiant_price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order',
            new_name='order_no',
        ),
    ]
