# Generated by Django 4.2.2 on 2023-07-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0010_remove_order_payment_remove_orderproduct_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.FloatField(),
        ),
    ]
