# Generated by Django 4.2.2 on 2023-07-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
