# Generated by Django 4.2.2 on 2023-07-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0017_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_status',
            new_name='product_status',
        ),
    ]
