# Generated by Django 4.2.2 on 2023-07-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0019_profile_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='product_image',
            new_name='profile_image',
        ),
    ]
