# Generated by Django 4.2.2 on 2023-08-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0020_rename_product_image_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='orderapp.order'),
        ),
    ]
